# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoCodex
                                 A QGIS plugin
 An AI assistant that help you in common tasks with qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-28
        copyright            : (C) 2025 by Amro, Ahmad
        email                : amro.eidd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

plugin_dir = os.path.dirname(__file__)
vendor_dir = os.path.join(plugin_dir, 'vendor')
if vendor_dir not in sys.path:
    sys.path.insert(0, vendor_dir)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoCodex class from file GeoCodex.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_codex import GeoCodex
    return GeoCodex(iface)
