# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoCodexDialog
                                 A QGIS plugin
 An AI assistant that help you in common tasks with qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-28
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Amro, Ahmad
        email                : amro.eidd@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QDialog
from qgis.core import QgsVectorLayer, QgsProject
from urllib.parse import quote_plus # For safely encoding the SQL query
# --- Import QGIS logging tools ---
from qgis.core import QgsMessageLog, Qgis
from .geo_codex_logic.orchestrator import WorkflowOrchestrator

from .geo_codex_logic.core.llm_client import LLMClient
from .geo_codex_logic.core.db_connector import DBConnector
from .geo_codex_logic.utils import prompt_builder

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ai_agent_dialog.ui'))

class GeoCodexDialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(GeoCodexDialog, self).__init__(parent)
        self.setupUi(self)
        self.testConnectionBtn.clicked.connect(self.on_test_connections_click)

        # The objectName 'generateSqlBtn' comes from your .ui file
        self.generateSqlBtn.clicked.connect(self.on_generate_sql_click)
        # Connect the 'Execute' button ---
        self.executeSqlBtn.clicked.connect(self.on_execute_sql_click)

    def on_test_connections_click(self):
        log = lambda msg: QgsMessageLog.logMessage(str(msg), 'GeoCodex', Qgis.Info)
        log("--- 'Test Connections' button clicked ---")
        # --- 1. Get all credentials from the UI input fields ---
        api_key = self.apiKeyInput.text()
        db_host = self.dbHostInput.text()
        db_port = self.dbPortInput.text()
        db_name = self.dbNameInput.text()
        db_user = self.dbUserInput.text()
        db_pass = self.dbPassInput.text()

        # --- 2. Test the LLM Connection ---
        self.statusLabel.setText("Status: Testing LLM connection...")
        try:
            llm_client = LLMClient(api_key=api_key)
            llm_success, llm_message = llm_client.test_connection()
        except Exception as e:
            # If the __init__ itself fails, this will catch it.
            log(f"CRITICAL: An exception occurred while creating LLMClient instance: {e}")
            llm_success, llm_message = False, str(e)

        if not llm_success:
            self.statusLabel.setText(f"Status: LLM Error - {llm_message}")
            log(f"Stopping due to LLM error: {llm_message}")
            return

        self.statusLabel.setText("Status: LLM OK. Testing database connection...")

        # --- 3. Test the Database Connection ---
        try:
            db_connector = DBConnector(
                host=db_host,
                port=db_port,
                dbname=db_name,
                user=db_user,
                password=db_pass
            )
            db_success, db_message = db_connector.test_connection()
        except Exception as e:
            db_success, db_message = False, str(e)
            
        if not db_success:
            self.statusLabel.setText(f"Status: DB Error - {db_message}")
            return

        # --- 4. Report final success ---
        self.statusLabel.setText("Status: Success! Both LLM and Database connections are working.")

    def _get_orchestrator(self):
        """ Helper method to create an orchestrator with current credentials. """
        api_key = self.apiKeyInput.text()
        db_params = {
            "host": self.dbHostInput.text(),
            "port": self.dbPortInput.text(),
            "dbname": self.dbNameInput.text(),
            "user": self.dbUserInput.text(),
            "password": self.dbPassInput.text()
        }
        return WorkflowOrchestrator(api_key, db_params)

    def on_generate_sql_click(self):
        self.statusLabel.setText("Status: Starting SQL generation...")
        user_query = self.userQueryInput.toPlainText()
        if not user_query:
            self.statusLabel.setText("Status: Please enter a question.")
            return

        orchestrator = self._get_orchestrator()
        success, result = orchestrator.run_nl_to_sql_workflow(user_query)

        if success:
            self.sqlResultOutput.setPlainText(result)
            self.statusLabel.setText("Status: SQL generated successfully! Please review.")
        else:
            self.statusLabel.setText(f"Status: Error - {result}")

    def on_execute_sql_click(self):
        self.statusLabel.setText("Status: Executing query...")
        sql_query = self.sqlResultOutput.toPlainText()
        if not sql_query:
            self.statusLabel.setText("Status: No SQL query to execute.")
            return

        layer_name = self.userQueryInput.toPlainText()[:30] or "AI Generated Layer"
        orchestrator = self._get_orchestrator()
        success, message = orchestrator.run_sql_to_layer_workflow(sql_query, layer_name)

        self.statusLabel.setText(f"Status: {message}")